/*
DROP TABLE PedidoAdicional;
DROP TABLE Pedido;
GO 
--*/
CREATE TABLE Pedido
(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	TamanhoId UNIQUEIDENTIFIER NOT NULL,
    SaborId UNIQUEIDENTIFIER NOT NULL,
    TempoDePreparo INT NOT NULL,
    PrecoTotal DECIMAL(9,2) NOT NULL,

    CONSTRAINT FK_Pedido_Tamanho FOREIGN KEY (TamanhoId) REFERENCES Tamanho(Id),
    CONSTRAINT FK_Pedido_Sabor FOREIGN KEY (SaborId) REFERENCES Sabor(Id)
);
GO
