/*
DROP TABLE Adicional;
GO 
--*/
CREATE TABLE Adicional
(
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	Label NVARCHAR(30) NOT NULL,
	Preco DECIMAL(9,2) NULL,
	TempoDePreparo INT NULL
);
GO
